version: "3"
services:
  postgres:
    image: "postgres:13.3"
    container_name: "city_philharmonic_db"
    environment:
      POSTGRES_DB: "city_philharmonic_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: